[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
qalam = "0.2.1"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

